version: '3.1'
services:
  concourse-db:
    image: postgres:9.5
    volumes: ["${DB_LOCAL_PATH}:/database"]
    networks:
      - service-tier
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "{PG_DATA}"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    networks:
      - service-tier
    command: web
    depends_on: [concourse-db]
    ports:
      - 8080:8080
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: "${CONCOURSE_USERNAME}"
      CONCOURSE_BASIC_AUTH_PASSWORD: "${CONCOURSE_PASSWORD}"
      CONCOURSE_EXTERNAL_URL: "https://build.bytecodetechnologies.com/"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: "${DB_USER}"
      CONCOURSE_POSTGRES_PASSWORD: "${DB_PASSWORD}"
      CONCOURSE_POSTGRES_DATABASE: "${DB_NAME}"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    networks:
      - web-tier
      - service-tier
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
    dns:
      - 8.8.8.8
      - 8.8.4.4
networks:
  web-tier:
  service-tier:

